actionid=py2.7
msg=installpkg
cmdargs=[local('/Users/esperyong/Develop/pyprojects/hwbuluo-gis/.tox/py2.7/bin/pip'), 'install', '--pre', '-U', '--no-deps', '/Users/esperyong/Develop/pyprojects/hwbuluo-gis/.tox/dist/hwbuluo-gis-0.0.1.zip']
env={'PYTHONIOENCODING': 'utf_8', 'VERSIONER_PYTHON_PREFER_32_BIT': 'no', 'TERM_PROGRAM_VERSION': '326', 'LOGNAME': 'esperyong', 'USER': 'esperyong', 'PATH': '/Users/esperyong/Develop/pyprojects/hwbuluo-gis/.tox/py2.7/bin:/Users/esperyong/Develop/pyprojects/hwbuluo-gis/venv/bin:/usr/local/Cellar/mysql55/5.5.30/bin:/Users/esperyong/bin/:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin', 'HOME': '/Users/esperyong', 'PS1': '(venv)\\h:\\W \\u\\$ ', 'TERM_PROGRAM': 'Apple_Terminal', 'LANG': 'zh_CN.UTF-8', 'TERM': 'xterm-256color', 'Apple_PubSub_Socket_Render': '/tmp/launch-dgl36C/Render', 'VERSIONER_PYTHON_VERSION': '2.7', 'SHLVL': '1', 'PYTHONHASHSEED': '2335035791', '_': '/Users/esperyong/Develop/pyprojects/hwbuluo-gis/venv/bin/tox', 'SVN_EDITOR': 'vi', 'TERM_SESSION_ID': '74A67292-B22D-420E-8A4D-010DE10942F6', 'SSH_AUTH_SOCK': '/tmp/launch-EN2o0w/Listeners', 'VIRTUAL_ENV': '/Users/esperyong/Develop/pyprojects/hwbuluo-gis/venv', 'DYLD_LIBRARY_PATH': '/usr/local/Cellar/mysql55/5.5.30/lib/', 'SHELL': '/bin/bash', 'VERSIONER_PYTHON_PREFER_64_BIT': 'yes', 'TMPDIR': '/var/folders/z0/ftwxm8cj07db5903d26lj78w0000gn/T/', 'OLDPWD': '/Users/esperyong/develop/pyprojects', '__CF_USER_TEXT_ENCODING': '0x1F5:25:52', 'PWD': '/Users/esperyong/develop/pyprojects/hwbuluo-gis', '__CHECKFIX1436934': '1'}
Unpacking ./.tox/dist/hwbuluo-gis-0.0.1.zip
  Running setup.py (path:/var/folders/z0/ftwxm8cj07db5903d26lj78w0000gn/T/pip-Er2t98-build/setup.py) egg_info for package from file:///Users/esperyong/Develop/pyprojects/hwbuluo-gis/.tox/dist/hwbuluo-gis-0.0.1.zip
    [ERROR] Cannot find file specified as ``long_description`` (README.mkd)
    
Installing collected packages: hwbuluo-gis
  Found existing installation: hwbuluo-gis 0.0.1
    Uninstalling hwbuluo-gis:
      Successfully uninstalled hwbuluo-gis
  Running setup.py install for hwbuluo-gis
    [ERROR] Cannot find file specified as ``long_description`` (README.mkd)
    
Successfully installed hwbuluo-gis
Cleaning up...
